# -*- coding: utf-8 -*-
"""Untitled5.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1i9vaKSrQ9huZqi1ZRYL7snvJ5qGuHyi2

ENCODING

1.   ASCII
2.   Unicode
under unicode we have utf8 and utf 16.
"""

string = '''Hola! Yo empecÃ© aprendo EspaÃ±ol hace dos mes en la escuela. Yo voy la universidad. Yo tratar estudioso EspaÃ±ol tres hora todos los dÃ*as para que yo saco mejor rÃ¡pido. Â¿Cosa algÃºn yo debo hacer ademÃ¡s construir mÃ* vocabulario? Muchas veces yo estudioso la palabras solo para que yo construir mÃ* voabulario rÃ¡pido. 
Yo quiero empiezo leo el periÃ³dico EspaÃ±ol la prÃ³xima semana. Por favor correcto algÃºn la equivocaciÃ³nes yo hisciste. Gracias! What I wanted to say:Hello I started learning Spanish a few months ago in school.I go to college. I try to study Spanish 3 hours everyday so I get better fast. 
Is there anything else I should do besides build vocabulary? Most of the time I study words to build my vocabulary fast.
 I want to focus on rules later. In a few weeks I want to start reading Spanish newspapers. Please correct any mistakes I made! Thanks'''

print(string)

with open('file.txt','w',encoding='utf8') as f:
  f.write(string)

with open('file.txt','r',encoding='utf8') as f:
  print(f.read())

"""STRING OPERATIONS:"""

sample = "This is my first session on Nlp 1"

sample[0]

sample[-1]

sample[-3]

"""SLICING"""

sample[:7]

sample[:9]

sample2 = "I hope this is making sense"

sample+" " +sample2

"""Methods on strings."""

sample.upper()

sample.lower()

len(sample)

sample.find('nlp')

"""FORMAT OUTPUT."""

s1 = "SAMPLE STRING"
X = 1

print ('This is the',s1,'for session',X)

print ('This is the{}for session{}'.format(s1,X))

"""Regex"""

import re

print(sample)

x = re.search("^this",sample)

x.group()

space = sample[8:11]

space.strip()

re.findall("(\w+)",sample)